### ISSUE TITLE
Bug: can't increase memory available to PHP

### ISSUE THREAD

**Issue by BurningDog** [CircleCI-Public/cimg-php#130]
I'm using the `cimg/php:7.4-node` image. Earlier today I was able to run CircleCI builds just fine e.g. https://circleci.com/bb/hupla/hupla-core-app/1035

However, a few hours ago I started getting out-of-memory errors when running `composer install -n --prefer-dist`:

```
[2021-11-19 16:05:02] php.CRITICAL: Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) at /home/circleci/symfony/var/cache/dev/twig/cb/cbc5ad8ba75fc3f306417edfdf5fd81dee57862f2a73a152ab0e8e4aeb81af35.php:1184)"} []
!! 
```

It looks like I'm not longer able to set memory to `-1` - or, indeed, any value. 

`php -d memory_limit=-1 /usr/local/bin/composer install -n --prefer-dist` fails with the above error. As does
`php -d memory_limit=512M /usr/local/bin/composer install -n --prefer-dist`.

It looks like _any_ adjusting of memory within CircleCI now fails?

The article at https://support.circleci.com/hc/en-us/articles/360040700954-Increasing-PHP-s-memory-limit is no longer helpful, as `/usr/local/etc/php/conf.d/docker-php-memlimit.ini` does not exist.

When running `php --ini` as part of the build I get:

```
Configuration File (php.ini) Path: /usr/local/lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

So instead, I've tried the following in my `.circleci/config.yml`:

```
      - run:
          name: Increase PHP memory
          command: echo 'memory_limit = -1' | sudo tee -a /usr/local/lib/php.ini
```

This worked.

This needs to be documented somewhere, for others to find.

**Comment by felicianotech** [comment]
Thank you for this info. I'll follow up once this is documented/determined what to do with this.

**Comment by felicianotech** [comment]
So, it looks like you want to set the memory limit to unlimited, and before the change today, that's actually what it was.

So the plan is:

1. Set the memory limit to unlimitted (-1) again. Right now it's unset and thus, uses the default.
2. We need to update the readme to include info on how to change this limit if someone wants to.
3. I can reach out to our Support Team to get that Support Article updated as I can't personally update it myself.


Did I miss anything? Sound reasonable?

**Comment by felicianotech** [comment]
3 of the 6 tags have been updated with the memory limit bumped back up. The other 3 will be updated within 20 minutes. You can read my post in the other issue for more details: https://github.com/CircleCI-Public/cimg-php/issues/126#issuecomment-974564054

**Comment by felicianotech** [comment]
This issue should be resolved as of a few days ago. If there's a follow up related to recent change, please add it to #126 while it's still open. If it closes, then you can start a new issue.

Thank you for taking the time to report.
