### ISSUE TITLE
latest version of php 7.4 doesn't have gd

### ISSUE THREAD

**Issue by generalredneck** [CircleCI-Public/cimg-php#131]
On all our builds that are running cimg/7.4. As of the latest build at https://hub.docker.com/layers/cimg/php/7.4.26/images/sha256-09ed3c06a99cd18b63bfc3d7a6bef226b070013079b3dff2d1e143b674290b4c
Composer no longer seems to think GD is installed. 

on 7.4.26
```
circleci@a46bf100dbd6:~/project$ php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]


```
same on 7.4.25

on 7.4.24
```
$ docker run -it cimg/php:7.4.24
Unable to find image 'cimg/php:7.4.24' locally
7.4.24: Pulling from cimg/php
c549ccf8d472: Pull complete 
d991028e4759: Pull complete 
45fcd6b49380: Pull complete 
7ffade9e8639: Pull complete 
3a82d4b10c68: Pull complete 
0f54edf2c183: Pull complete 
5c2ee9d4e797: Pull complete 
670ee2a4d488: Pull complete 
d85ece2da328: Pull complete 
Digest: sha256:ee2a0a49e56f81b676f6ba72691149ebde700571e659af27227f723a65efa767
Status: Downloaded newer image for cimg/php:7.4.24
circleci@4a74b134e988:~/project$ php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd          #<------------This is what we are looking for.
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by generalredneck** [comment]
For those having this issue... You may be able:
* to go the route described in https://github.com/docker-library/php/issues/750#issuecomment-439364320 with `sudo -E docker-php-ext-install gd`. 
* You can pin to cimg/php:7.4.24 or depending on what's failing... 
* doing something like `composer install --ignore-platform-req=ext-gd` which was the case for some of our static testing jobs.

**Comment by generalredneck** [comment]
It looks like we can trace it back to this commit.
https://github.com/CircleCI-Public/cimg-php/commit/232cec6174116600f50055f19729c6762fe37892#diff-1550114f57de033bab7e47d870ee40e39290e808c139822218e20ec60c346ee5

**Comment by felicianotech** [comment]
You're using a testing image at the moment. Please see #126 . I've already got this fix for this queued up so the next image update for 7.4.26 (soon, today) will include gd. I'm gathering the feedback from a few other things first before I go ahead and publish.

**Comment by generalredneck** [comment]
Ok, using the PHP circle orb (or for most people) using the dockerimage cimg/php:7.4 will have downloaded this version. I don't know how to continue to get the updates and avoid testing images like todays. having CI just fail randomly across all our clients was pretty hard core...

**Comment by felicianotech** [comment]
Here's my thoughts:

1. Don't use an alias tag (such as `:7.4`) as those tags can (and are designed to) change. I would use a specific PHP version tag, such as `:7.4.26`.
2. This type of image publish is very rare. This happened for a few new versions of PHP currently because we're having problems with the build process for this image that we need to fix moving forward.
3. In 2022, we going to introduce a completely different Docker Hub namespace for testing images to prevent this from happening. Right now we only have the single namespace to test.

I hope that helps with your confidence in the image publishing process.

**Comment by generalredneck** [comment]
Thank you tons for the work and the quick feedback!

**Comment by felicianotech** [comment]
The image `cimg/php:7.4.25` should be updated by now and `cimg/php:7.4.26` in the near future once I get it reviewed and merged.

**Comment by felicianotech** [comment]
Newer tags published with the new PHP should all be ready within 30 minutes or so. I'll leave this Issue open until early next week to give some time for confirmation.

**Comment by felicianotech** [comment]
This issue should be resolved as of a few days ago. If it's not, please report it in #126 if it's still open. Otherwise, a new Issue. For the record, gd as well as many other extensions where compiled in with this process so I assume we have the basics covered now.

Thank you for reporting.
