### ISSUE TITLE
Install XSL extension

### ISSUE THREAD

**Issue by garak** [CircleCI-Public/cimg-php#163]
I migrated from old version of CircleCI image to cimg/php:7.4 and now I have a problem in a project where I need php-xsl extension.

I tried to manually install it by using `sudo apt update && sudo apt install -qqy --no-install-recommends libxslt-dev php-xsl` but it doesn't work: even if during the process I see a line containing `Creating config file /etc/php/7.4/mods-available/xsl.ini with new version`, when I run `composer install` if fails with `[redacted-vendor] 1.x.x requires ext-xsl * -> it is missing from your system. Install or enable PHP's xsl extension`.

**Comment by JalexChen** [comment]
Hi @garak - there is a PR in that will address this.

`sudo apt update && sudo apt install -qqy --no-install-recommends libxslt-dev php-xsl && \
sudo -E install-php-extensions xsl` should enable this for you.

**Comment by barryvdh** [comment]
Running into the same issue. Not sure how to enable xsl, as it's installed by default but not enabled?

**Comment by JalexChen** [comment]
Hi @barryvdh, XSL is _bundled_, but it is not installed or enabled by default in this image. With the new PR, you would be able to use `sudo apt update && sudo apt install -qqy --no-install-recommends libxslt-dev php-xsl && \ sudo -E install-php-extensions xsl` to install and enable it.

**Comment by JalexChen** [comment]
Hi @garak and @barryvdh, I've created a couple of test images for php with some additional functionality described [here](https://github.com/CircleCI-Public/cimg-php/issues/175). If you could give those a run and give us some feedback on if it works for your use-case or whether there might need to be changes, that would be greatly appreciated

**Comment by barryvdh** [comment]
With the 7.4 test it seems to work :) Can install without ignoring the platform reqs.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/973269/173019535-e6900237-a3f4-4415-9d1a-23273aab326c.png">

**Comment by garak** [comment]
Works for me too

**Comment by garak** [comment]
@JalexChen thanks for this, but I don't see any changes in the repository README. So the feature is available, but no one knows (except us, I guess)

**Comment by JalexChen** [comment]
hey @garak - There's a pull request in for it. Will have it in shortly
