### ISSUE TITLE
Install Gmp extension 

### ISSUE THREAD

**Issue by yamenarahman** [CircleCI-Public/cimg-php#165]
I was able to add this command `sudo apt install php-gmp`, but composer fails to complete installation because I require `ext-gmp` and the error message is like 'Install gmp or enable gmp'.

**Comment by ahmadabdallah** [comment]
@JalexChen @felicianotech  can you guys please support on this . how we can install this extension

**Comment by JalexChen** [comment]
hi @ahmadabdallah - a fix is in the works to include a way to install and configure exts. As a workaround, the --with-gmp flag can be added to the provided Dockerfile in order to enable it.

**Comment by yamenarahman** [comment]
@JalexChen Thanks for the reply, but where to add this flag `--with-gmp`?

**Comment by joel-loycom** [comment]
Could we get an estimation on when this will be ready?  we are also having this issue and we wonder if it worth to look for a way around or wait for the fix
