### ISSUE TITLE
sudo: docker-php-ext-enable: command not found

### ISSUE THREAD

**Issue by Poonam0311** [CircleCI-Public/cimg-php#166]
On replacing the old image (circleci/php:7.4-node) with the new one(cimg/php:7.4-node), the circleci tests fail due to the below error:

sudo: docker-php-ext-enable: command not found

**Comment by JalexChen** [comment]
Hi @Poonam0311 - these commands are not included on the new Cimgs and we are looking into adding this functionality.

**Comment by joel-loycom** [comment]
Could we get an estimation on adding that? right now this is preventing us from using circle at the moment..

**Comment by JalexChen** [comment]
Hi @acorncom and @joel-loycom - currently working on this and I'm hoping to get a PR out this week with the docker-php-ext-* commands available. Currently testing to ensure core and pecl extension installs are working correctly.

**Comment by joel-loycom** [comment]
That's awesome! thank you!

**Comment by JalexChen** [comment]
@acorncom there is currently a PR up that you can check out: `gh pr checkout 172`. I specifically used your previous example, but it would be great for additional tests against your use case!

**Comment by JalexChen** [comment]
Hi @acorncom @joel-loycom @Poonam0311 

I've created three different versions of php for testing [here](https://github.com/CircleCI-Public/cimg-php/issues/175).

If any of these versions/images are applicable to you, I would love if you could test them out for your use cases and report back on if any changes need to be made. 

Appreciate it.
