### ISSUE TITLE
Can you help test php-extensions functionality?

### ISSUE THREAD

**Issue by JalexChen** [CircleCI-Public/cimg-php#175]
Hi Everyone, I've added some of the requested functionality for install-php-extensions (mclocati's script) as well as the php team's docker helper functions to address some concerns about installing and/or enabling core and additional extensions

However, I would love to receive some feedback on whether or not this is working as intended for everyone as use cases could be different.

There are three different versions of the test images
cimg/php:7.4.29-ext-test
cimg/php:8.0.19-ext-test
cimg/php:8.1.5-ext-test

the commands/functionality in question include:

`sudo -E install-php-extensions xsl xdebug` the -E flag may need to be used in certain cases where environment variables need to be preserved

`install-php-extensions` wraps and uses the following commands, but you may also use/test them separately

`sudo docker-php-source extract`
`sudo docker-php-ext-install iconv`
`sudo -E docker-php-ext-enable iconv`
`docker-php-source delete`

**Comment by barryvdh** [comment]
The 7.4 test seems to work for me. Builds and is able to install the xls extension:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/973269/173019622-caed9991-9aaa-4a9e-9e65-56caf881cac8.png">
