### ISSUE TITLE
Documentation on how to build a image might need to be updated

### ISSUE THREAD

**Issue by rodrigoprimo** [CircleCI-Public/cimg-php#199]
I'm running into the following error when trying to build an image using the instructions in the README file (https://github.com/CircleCI-Public/cimg-php#generating-dockerfiles):

```
$ cd 7.4
$ docker build -t test/php:7.4.26 .
(...)
Step 8/12 : COPY /docker-php-scripts/docker-php-* /usr/local/bin/
COPY failed: no source files were specified
```

I have a very basic knowledge of Docker so I might be missing something, but I believe there is a chance that the documentation needs to be updated as the directory `docker-php-scripts` doesn't exist inside `7.4`, but instead it is located in the root of the repository. I can successfully build the image if I run the following from the root of the repository:

```
$ docker build --file 7.4/Dockerfile -t test/php:7.4.26 .
```

**Comment by JalexChen** [comment]
Hey @Rodrigo - this is working as intended. you wouldn't need to cd into a directory to build an image as you would want to run it from root _because_ of the references to external directories like docker-php-scripts.

**Comment by rodrigoprimo** [comment]
@JalexChen, thanks for your response. I'm sorry if my original message was not clear or if I'm still missing something, but since you confirmed that it is not necessary to cd into a directory to build an image, I guess it would be a good idea to update the part of the documentation that instruct users to cd into a directory to build an image?

https://github.com/CircleCI-Public/cimg-php#generating-dockerfiles

**Comment by JalexChen** [comment]
hey @rodrigoprimo - you're absolutely right. i think these docs weren't updated because the docker php extension was added afterwards.
