### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by peter279k** [CircleCI-Public/cimg-php#2]
As title, this repository misses the `README`.

I think we can consider initializing the `README` to guide developers.

Once this issue is accepted, I can work on this and please add `#orbtoberfest` on this issue because of the [hacktoberfest circleci](https://hacktoberfest.circleci.com) :).

**Comment by felicianotech** [comment]
Hi @peter279k, 

Still willing to tackle this? This README should be based on the format that https://github.com/CircleCI-Public/cimg-go uses, but with the details changed for PHP.

**Comment by crweiner** [comment]
@felicianotech I created the first draft of a `README` file in PR #8 based on your recommendation to use the [cimg-go](https://github.com/CircleCI-Public/cimg-go) repo as the jumping off point.
