### ISSUE TITLE
Install latest version of Composer

### ISSUE THREAD

**Issue by brunogaspar** [CircleCI-Public/cimg-php#203]
Hello :)

Wouldn't it be to install always the latest version of Composer?

The version being installed has deprecation issues on PHP 8.2 while the current version of Composer 2.4.4 has this addressed already.

I could submit a PR to bump to the latest version on the 8.2 Dockerfile, but i'm wondering what would be preferred.

**Comment by JalexChen** [comment]
hi @brunogaspar - thanks for the note. I'm unsure if we have any php experts on the team, so your expertise is well appreciated. 

we would love for you to contribute and make a PR. the only thing i would ask is for you to update the version `Dockerfile.template`, as opposed to the 8.2 `Dockerfile` specifically, so any future releases can use that version of the composer. 

if you are running into issues with your current builds, we can look into cutting a new release if it is also affecting others for 8.2

**Comment by brunogaspar** [comment]
Hello @JalexChen 

Yes, i've ran into some CI issues the other day when running for example `php-cs-fixer` so i've addressed this issue for now by running `composer self-update` to allow the runs to be green.

Will look into submitting a PR as you recommended to that file :)
