### ISSUE TITLE
Add docker-php-ext-install command

### ISSUE THREAD

**Issue by edlouth** [CircleCI-Public/cimg-php#53]
circleci/php:7.3 allows the use of docker-php-ext-install to easily install additional php extensions. Could this be added to this image to allow for the easy installation of php extensions?

**Comment by felicianotech** [comment]
Definitely a possibility. Can you provide an example of an extension you'd want to install?

**Comment by edlouth** [comment]
I currently install the following extensions:
zip gd pdo_mysql bcmath calendar pcntl sockets
This allows me to run composer install without getting errors for missing extensions

**Comment by felicianotech** [comment]
Hi. For now we're not going to move forward with this. Will consider it in the future.

Most next-gen PHP images contains almost everything you mentioned. The images released today contain bcmath which completes your list.

Many extensions can be installed via Apt and other popular methods for Ubuntu.

**Comment by dneukirchen** [comment]
Hi @felicianotech, it would be nice to have bcmath also in 5.x and 7.2.x so that the versions are interchangeable without any further steps.

**Comment by AlexSkrypnyk** [comment]
I need to configure an extension in a certain way and old images had the command to do so.
`sudo -E docker-php-ext-configure gd --with-freetype --with-jpeg;`
If new images do not have the same command, could you please at least point to an alternative.
Thank you
