### ISSUE TITLE
Feature Request: Install / Enable `phpdbg`

### ISSUE THREAD

**Issue by TangRufus** [CircleCI-Public/cimg-php#97]
The [docs](https://circleci.com/docs/2.0/code-coverage/#php) implies `phpdbg` is available in the docker images. However:

```sh-session
$ docker run --rm -it cimg/php:8.0 bash
circleci@3479102d86ae:~/project$ phpdbg
bash: phpdbg: command not found


$ docker run --rm -it cimg/php:7.4 bash
circleci@6cdc5c59a603:~/project$ phpdbg
bash: phpdbg: command not found

$ docker run --rm -it cimg/php:7.3 bash
circleci@ecdc88794269:~/project$ phpdbg
bash: phpdbg: command not found
```

**Comment by felicianotech** [comment]
The doc is referring to the legacy PHP image (`circleci/php`), not the next-gen PHP image (`cimg/php`) for which this repo is.

I've opened a PR to add this tool though. Please keep in mind, we don't update old SemVer tags with next-gen images. This means that even when my PR is merged, you won't see if it an image until we publish new PHP releases. So the next versions of PHP 7.x and 8.x will get this whenever they are released by PHP.net.

**Comment by felicianotech** [comment]
Oh and I forgot to say, thank you for opening this Issue. We appreciate it. :slightly_smiling_face:

**Comment by TangRufus** [comment]
Thanks!!! #98 looks good!

**Comment by TangRufus** [comment]
Question: How often does [`cimg/php`](https://hub.docker.com/r/cimg/php/tags?page=1&ordering=last_updated) got updated?

**Comment by felicianotech** [comment]
As often as PHP.net makes a release.
